const EC = require("elliptic").ec;
const ec = new EC("secp256k1");
const Transaction = require('./Transaction');
const Blockchain = require("./Blockchain");
const TransactionPool = require("./transaction-pool");

class Wallet{

    constructor(){
        this.balance = 500;
        this.keyPair = ec.genKeyPair();
        this.publicKey = this.keyPair.getPublic().encode('hex');
    }

    sign(dataHash){
        return this.keyPair.sign(dataHash)
    }

    createTransaction(recipient, amount,blockchain, transactionPool){

        this.balance = this.calculateBalance(blockchain);

        if(amount > this.balance){
            console.log(`Amount: ${amount} exceeds the current balance: ${this.balance}`);
            return;
        }

        let transaction = transactionPool.existingTransaction(this.publicKey);

        if(transaction){
            // creates more outputs
            transaction.update(this,recipient,amount)
        }
        else{
            // creates a new transaction and updates the transaction pool
            transaction = Transaction.newTransaction(this,recipient,amount);
            transactionPool.updateOrAddTransaction(transaction);
        }

        return transaction;

    }

    calculateBalance(blockchain){
        
        // store the existing balance
        let balance = this.balance;

        // create an array of transactions
        let transactions = [];

        // store all the transactions in the array
        blockchain.chain.forEach(block => block.data.forEach(transaction =>{
            transactions.push(transaction);
        }));

        // get all the transactions generated by the wallet ie money sent by the wallet
        const walletInputTransactions = transactions.filter(transaction => transaction.input.address === this.publicKey);

        // declare a variable to save the timestamp
        let startTime = 0;

        if(walletInputTransactions.length > 0){

            // get the latest transaction
            const recentInputTransaction = walletInputTransactions.reduce((prev,current)=> prev.input.timestamp > current.input.timestamp ? prev : current );
            
            // get the outputs of that transactions, its amount will be the money that we would get back
            balance = recentInputTransaction.outputs.find(output => output.address === this.publicKey).amount

            // save the timestamp of the latest transaction made by the wallet
            startTime = recentInputTransaction.input.timestamp
        }

        // get the transactions that were addressed to this wallet ie somebody sent some moeny
        // and add its ouputs.
        // since we save the timestamp we would only add the outputs of the transactions recieved
        // only after the latest transactions made by us

        transactions.forEach(transaction =>{
            if(transaction.input.timestamp > startTime){
                transaction.outputs.find(output=>{
                    if(output.address === this.publicKey){
                        balance += output.amount;
                    }
                })
            }
        })
        return balance;

    }

}

module.exports = Wallet;

const blockchain = new Blockchain();
const wallet1 = new Wallet();
const wallet2 = new Wallet();
const transactionPool = new TransactionPool();

console.log(wallet1);
console.log(wallet2);




balance = wallet2.calculateBalance(blockchain)
const transaction = wallet1.createTransaction(wallet1.publicKey, 500 ,blockchain,transactionPool);
console.log(transaction);
blockchain.addBlock(transaction);

console.log();




